name: Compile ztecfg

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: '3.8'
  PYTHON_FILE: 'ztecfg.py'

jobs:
  build:
    name: Build Execute File
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup version variables
        shell: bash
        run: |
          BUILD_TAG=`git describe --tags || echo v0.1.0`
          BUILD_DATE=`date +"%Y%m%d"`
          BUILD_HASH=`git rev-parse --short HEAD`
          echo "::set-env name=BUILD_TAG::$BUILD_TAG"
          echo "::set-env name=BUILD_DATE::$BUILD_DATE"
          echo "::set-env name=BUILD_HASH::$BUILD_HASH"
          echo "::set-env name=BUILD_VERSION::$BUILD_TAG+$BUILD_DATE.$BUILD_HASH"

      - name: Update version (Linux / Windows)
        if: matrix.os != 'macos-10.15'
        shell: bash
        run: |
          sed -i 's/{VERSION}/${{ env.BUILD_VERSION }}/' ${{ env.PYTHON_FILE }}

      - name: Update version (macOS)
        if: matrix.os == 'macos-10.15'
        run: |
          sed -i '' 's/{VERSION}/${{ env.BUILD_VERSION }}/' ${{ env.PYTHON_FILE }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install depdendencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          [ -e requirements.txt ] && pip install -r requirements.txt

      - name: Compile
        run: |
          pyinstaller --onefile ${{ env.PYTHON_FILE }}

      - name: Upload Artifact (Linux)
        if: matrix.os == 'ubuntu-18.04'
        uses: actions/upload-artifact@v2
        with:
          name: ztecfg_${{ env.BUILD_TAG }}_linux
          path: dist/*

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-2019'
        uses: actions/upload-artifact@v2
        with:
          name: ztecfg_${{ env.BUILD_TAG }}_win
          path: dist/*

      - name: Upload Artifact (macOS)
        if: matrix.os == 'macos-10.15'
        uses: actions/upload-artifact@v2
        with:
          name: ztecfg_${{ env.BUILD_TAG }}_mac
          path: dist/*
