name: Compile ztecfg

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: '3.8'
  PYTHON_FILE: 'ztecfg.py'

jobs:
  prepare:
    name: Prepare environments
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup environments
        run: |
          TAG=`git describe --abbrev=0 --tags`
          TAG=${TAG:-'0.1.0'}
          echo "::set-env name=BUILD_TAG::$TAG"
          echo "::set-env name=BUILD_DATE::$(date +'%Y%m%d')"
          echo "::set-env name=BUILD_COUNT::$(git rev-list --count HEAD)"
          echo "::set-env name=BUILD_HASH::$(git rev-parse --short HEAD)"
          echo "::set-env name=BUILD_VERSION::$(echo $BUILD_TAG+b$BUILD_COUNT.$BUILD_HASH)"
        continue-on-error: true

  build:
    name: Build Execute File
    needs: prepare
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Update version (Linux)
        run: |
          sed -i 's/{VERSION}/${{ env.BUILD_VERSION }}/' ${{ env.PYTHON_FILE }}

      - name: Update version (Windows)
        run: |
          (Get-Content ${{ env.PYTHON_FILE }}).replace('{VERSION}', '${{ env.BUILD_VERSION }}') | Set-Content ${{ env.PYTHON_FILE }}

      - name: Update version (macOS)
        run: |
          sed -i '' 's/{VERSION}/${{ env.BUILD_VERSION }}/' ${{ env.PYTHON_FILE }}

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install depdendencies (Linux / macOS)
        if: matrix.os != 'windows-2019'
        run: |
          [ -e requirements.txt ] && pip install -r requirements.txt

      - name: Install depdendencies (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          if (Test-Path requirements.txt)
          {
            pip install -r requirements.txt
          }

      - name: Compile
        run: |
          pyinstaller --onefile ${{ env.PYTHON_FILE }}

      - name: Upload Artifact (Linux)
        if: matrix.os == 'ubuntu-18.04'
        uses: actions/upload-artifact@v2
        with:
          name: ztecfg_linux
          path: dist/*

      - name: Upload Artifact (Windows)
        if: matrix.os == 'windows-2019'
        uses: actions/upload-artifact@v2
        with:
          name: ztecfg_win
          path: dist/*

      - name: Upload Artifact (macOS)
        if: matrix.os == 'macos-10.15'
        uses: actions/upload-artifact@v2
        with:
          name: ztecfg_mac
          path: dist/*
